"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatresponse import ChatResponse, ChatResponseTypedDict
from .chatstreamingresponsechunk import (
    ChatStreamingResponseChunk,
    ChatStreamingResponseChunkTypedDict,
)
from openrouter.utils import eventstreaming
from typing import Union
from typing_extensions import TypeAliasType


SendChatCompletionRequestResponseTypedDict = TypeAliasType(
    "SendChatCompletionRequestResponseTypedDict",
    Union[
        ChatResponseTypedDict,
        Union[
            eventstreaming.EventStream[ChatStreamingResponseChunkTypedDict],
            eventstreaming.EventStreamAsync[ChatStreamingResponseChunkTypedDict],
        ],
    ],
)


SendChatCompletionRequestResponse = TypeAliasType(
    "SendChatCompletionRequestResponse",
    Union[
        ChatResponse,
        Union[
            eventstreaming.EventStream[ChatStreamingResponseChunk],
            eventstreaming.EventStreamAsync[ChatStreamingResponseChunk],
        ],
    ],
)
