"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel
from openrouter.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FileTypedDict(TypedDict):
    file_data: str
    file_id: NotRequired[str]
    filename: NotRequired[str]


class File(BaseModel):
    file_data: str

    file_id: Optional[str] = None

    filename: Optional[str] = None


class ChatMessageContentItemFileTypedDict(TypedDict):
    file: FileTypedDict
    type: Literal["file"]


class ChatMessageContentItemFile(BaseModel):
    file: File

    TYPE: Annotated[
        Annotated[Literal["file"], AfterValidator(validate_const("file"))],
        pydantic.Field(alias="type"),
    ] = "file"
