"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responseinputfile import ResponseInputFile, ResponseInputFileTypedDict
from .responseinputtext import ResponseInputText, ResponseInputTextTypedDict
from .toolcallstatus import ToolCallStatus
from openrouter.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from openrouter.utils import get_discriminator, validate_open_enum
from pydantic import Discriminator, Tag, model_serializer
from pydantic.functional_validators import PlainValidator
from typing import List, Literal, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


OpenResponsesFunctionCallOutputTypeFunctionCallOutput = Literal["function_call_output",]


OutputType = Literal["input_image",]


OpenResponsesFunctionCallOutputDetail = Union[
    Literal[
        "auto",
        "high",
        "low",
    ],
    UnrecognizedStr,
]


class OutputInputImageTypedDict(TypedDict):
    r"""Image input content item"""

    type: OutputType
    detail: OpenResponsesFunctionCallOutputDetail
    image_url: NotRequired[Nullable[str]]


class OutputInputImage(BaseModel):
    r"""Image input content item"""

    type: OutputType

    detail: Annotated[
        OpenResponsesFunctionCallOutputDetail, PlainValidator(validate_open_enum(False))
    ]

    image_url: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["image_url"]
        nullable_fields = ["image_url"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


OpenResponsesFunctionCallOutputOutputUnion1TypedDict = TypeAliasType(
    "OpenResponsesFunctionCallOutputOutputUnion1TypedDict",
    Union[
        ResponseInputTextTypedDict,
        OutputInputImageTypedDict,
        ResponseInputFileTypedDict,
    ],
)


OpenResponsesFunctionCallOutputOutputUnion1 = Annotated[
    Union[
        Annotated[ResponseInputText, Tag("input_text")],
        Annotated[OutputInputImage, Tag("input_image")],
        Annotated[ResponseInputFile, Tag("input_file")],
    ],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]


OpenResponsesFunctionCallOutputOutputUnion2TypedDict = TypeAliasType(
    "OpenResponsesFunctionCallOutputOutputUnion2TypedDict",
    Union[str, List[OpenResponsesFunctionCallOutputOutputUnion1TypedDict]],
)


OpenResponsesFunctionCallOutputOutputUnion2 = TypeAliasType(
    "OpenResponsesFunctionCallOutputOutputUnion2",
    Union[str, List[OpenResponsesFunctionCallOutputOutputUnion1]],
)


class OpenResponsesFunctionCallOutputTypedDict(TypedDict):
    r"""The output from a function call execution"""

    type: OpenResponsesFunctionCallOutputTypeFunctionCallOutput
    call_id: str
    output: OpenResponsesFunctionCallOutputOutputUnion2TypedDict
    id: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[ToolCallStatus]]


class OpenResponsesFunctionCallOutput(BaseModel):
    r"""The output from a function call execution"""

    type: OpenResponsesFunctionCallOutputTypeFunctionCallOutput

    call_id: str

    output: OpenResponsesFunctionCallOutputOutputUnion2

    id: OptionalNullable[str] = UNSET

    status: Annotated[
        OptionalNullable[ToolCallStatus], PlainValidator(validate_open_enum(False))
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["id", "status"]
        nullable_fields = ["id", "status"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
