"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcallstatus import ToolCallStatus
from openrouter.types import BaseModel
from openrouter.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


OutputSubAgentServerToolItemType = Literal["openrouter:subagent",]


class OutputSubAgentServerToolItemTypedDict(TypedDict):
    r"""An openrouter:subagent server tool output item"""

    status: ToolCallStatus
    type: OutputSubAgentServerToolItemType
    outcome: NotRequired[str]
    r"""The subagent model's response"""
    error: NotRequired[str]
    r"""Error message when the subagent call did not produce advice."""
    id: NotRequired[str]
    instance_name: NotRequired[str]
    r"""Provider-safe function name of the specific subagent instance that produced this item (e.g. `openrouter_subagent__1`). Present only when more than one subagent tool is configured; omitted for the default single subagent. Echo this field back unchanged so the subagent's cross-request memory stays namespaced to the correct instance. This identity is positional: it is derived from the index of the subagent entry in the request `tools` array, so clients must keep the order of subagent tool entries stable across requests in a conversation. Reordering or inserting subagent entries shifts these names and causes each subagent's cross-request memory to be attributed to the wrong instance."""
    model: NotRequired[str]
    r"""Slug of the subagent model that was consulted."""
    prompt: NotRequired[str]
    r"""The prompt the executor sent to the subagent."""


class OutputSubAgentServerToolItem(BaseModel):
    r"""An openrouter:subagent server tool output item"""

    status: Annotated[ToolCallStatus, PlainValidator(validate_open_enum(False))]

    type: OutputSubAgentServerToolItemType

    outcome: Optional[str] = None
    r"""The subagent model's response"""

    error: Optional[str] = None
    r"""Error message when the subagent call did not produce advice."""

    id: Optional[str] = None

    instance_name: Optional[str] = None
    r"""Provider-safe function name of the specific subagent instance that produced this item (e.g. `openrouter_subagent__1`). Present only when more than one subagent tool is configured; omitted for the default single subagent. Echo this field back unchanged so the subagent's cross-request memory stays namespaced to the correct instance. This identity is positional: it is derived from the index of the subagent entry in the request `tools` array, so clients must keep the order of subagent tool entries stable across requests in a conversation. Reordering or inserting subagent entries shifts these names and causes each subagent's cross-request memory to be attributed to the wrong instance."""

    model: Optional[str] = None
    r"""Slug of the subagent model that was consulted."""

    prompt: Optional[str] = None
    r"""The prompt the executor sent to the subagent."""
