"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subagentservertoolconfig import (
    SubAgentServerToolConfig,
    SubAgentServerToolConfigTypedDict,
)
from openrouter.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


SubAgentServerToolOpenRouterType = Literal["openrouter:subagent",]


class SubAgentServerToolOpenRouterTypedDict(TypedDict):
    r"""OpenRouter built-in server tool: consults a higher-intelligence subagent model (any OpenRouter model) for guidance mid-generation and returns its response. The subagent may run as a sub-agent with its own tools. Include multiple entries to offer several named advisors; at most one entry may omit `name` to act as the default subagent."""

    type: SubAgentServerToolOpenRouterType
    name:Optional[str]
    parameters: NotRequired[SubAgentServerToolConfigTypedDict]
    r"""Configuration for one openrouter:subagent server tool entry."""


class SubAgentServerToolOpenRouter(BaseModel):
    r"""OpenRouter built-in server tool: consults a higher-intelligence subagent model (any OpenRouter model) for guidance mid-generation and returns its response. The subagent may run as a sub-agent with its own tools. Include multiple entries to offer several named advisors; at most one entry may omit `name` to act as the default subagent."""

    type: SubAgentServerToolOpenRouterType
    name:Optional[str]
    parameters: Optional[SubAgentServerToolConfig] = None
    r"""Configuration for one openrouter:subagent server tool entry."""
