"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subagentnestedtool import SubAgentNestedTool, SubAgentNestedToolTypedDict
from .subagentreasoning import SubAgentReasoning, SubAgentReasoningTypedDict
from openrouter.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SubAgentServerToolConfigTypedDict(TypedDict):
    r"""Configuration for one openrouter:subagent server tool entry."""

    instructions: NotRequired[str]
    r"""System instructions for the subagent sub-agent. When omitted, the subagent responds with no system prompt of its own."""
    max_completion_tokens: NotRequired[int]
    r"""Maximum number of output tokens (including reasoning) the subagent may produce. When omitted, the provider's default applies."""
    max_tool_calls: NotRequired[int]
    r"""Maximum number of tool-calling steps the subagent sub-agent may take during its agentic loop. Capped at 25. Only relevant when the subagent is given tools."""
    model: NotRequired[str]
    r"""Slug of the subagent model to consult (any OpenRouter model). When omitted, the executor can choose it via the tool call's `model` argument; if neither is set, the model from the outer API request is used. The subagent tool itself cannot be the subagent model."""
    reasoning: NotRequired[SubAgentReasoningTypedDict]
    r"""Reasoning configuration forwarded to the subagent call. Use this to control reasoning effort and token budget for models that support extended thinking."""
    temperature: NotRequired[float]
    r"""Sampling temperature forwarded to the subagent call. When omitted, the provider's default applies."""
    tools: NotRequired[List[SubAgentNestedToolTypedDict]]
    r"""Tools the subagent sub-agent may use while forming its advice. The subagent runs as an agentic sub-agent over these tools, then returns its text. Must not include the subagent tool itself."""


class SubAgentServerToolConfig(BaseModel):
    r"""Configuration for one openrouter:subagent server tool entry."""

    
    instructions: Optional[str] = None
    r"""System instructions for the subagent sub-agent. When omitted, the subagent responds with no system prompt of its own."""

    max_completion_tokens: Optional[int] = None
    r"""Maximum number of output tokens (including reasoning) the subagent may produce. When omitted, the provider's default applies."""

    max_tool_calls: Optional[int] = None
    r"""Maximum number of tool-calling steps the subagent sub-agent may take during its agentic loop. Capped at 25. Only relevant when the subagent is given tools."""

    model: Optional[str] = None
    r"""Slug of the subagent model to consult (any OpenRouter model). When omitted, the executor can choose it via the tool call's `model` argument; if neither is set, the model from the outer API request is used. The subagent tool itself cannot be the subagent model."""

    reasoning: Optional[SubAgentReasoning] = None
    r"""Reasoning configuration forwarded to the subagent call. Use this to control reasoning effort and token budget for models that support extended thinking."""

    temperature: Optional[float] = None
    r"""Sampling temperature forwarded to the subagent call. When omitted, the provider's default applies."""

    tools: Optional[List[SubAgentNestedTool]] = None
    r"""Tools the subagent sub-agent may use while forming its advice. The subagent runs as an agentic sub-agent over these tools, then returns its text. Must not include the subagent tool itself."""
