"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openrouter.types import BaseModel, UnrecognizedStr
from openrouter.utils import validate_open_enum
from pydantic.functional_validators import PlainValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


SubAgentReasoningEffort = Union[
    Literal[
        "xhigh",
        "high",
        "medium",
        "low",
        "minimal",
        "none",
    ],
    UnrecognizedStr,
]
r"""Reasoning effort level for the subagent call."""


class SubAgentReasoningTypedDict(TypedDict):
    r"""Reasoning configuration forwarded to the subagent call. Use this to control reasoning effort and token budget for models that support extended thinking."""

    effort: NotRequired[SubAgentReasoningEffort]
    r"""Reasoning effort level for the subagent call."""
    max_tokens: NotRequired[int]
    r"""Maximum number of reasoning tokens the subagent may use."""


class SubAgentReasoning(BaseModel):
    r"""Reasoning configuration forwarded to the subagent call. Use this to control reasoning effort and token budget for models that support extended thinking."""

    effort: Annotated[
        Optional[SubAgentReasoningEffort], PlainValidator(validate_open_enum(False))
    ] = None
    r"""Reasoning effort level for the subagent call."""

    max_tokens: Optional[int] = None
    r"""Maximum number of reasoning tokens the subagent may use."""
